env:
  browser: true
  es2021: true

extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended']
plugins: ['@typescript-eslint']
parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    - jsx: true
  ecmaVersion: latest
  sourceType: module

rules:
  '@typescript-eslint/no-non-null-assertion': ['off']
  indent: ['error', 'tab']
  linebreak-style: ['error', 'unix']
  quotes: ['error', 'single']
  semi: ['error', 'never']
